openapi: 3.1.0
info:
  title: Sample API
  description: This is an example API to demonstrate feature flagging of APIs using OpenAPI extensions.
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
paths:
  /hello:
    get:
      summary: Returns a greeting message
      operationId: getGreeting
      x-feature-flag: greeting
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"